AirportManagementSystem/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AirportManagementSystem.Models;

namespace AirportManagementSystem.Controllers
{
    public class ManagerController : Controller
    {
        AirportManagementSystemContext db = new AirportManagementSystemContext();
        // GET: Manager
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ManagerHomePage()
        {
            return View("ManagerHomePage");
        }

        public ActionResult ListOfHangar()
        {

            return View(db.Hangers.ToList());
        }

        public ActionResult UpdateHangar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hangar hangar = db.Hangers.Find(id);
            if (hangar == null)
            {
                return HttpNotFound();
            }
            return View(hangar);
        }

        [HttpPost]
        public ActionResult UpdateHangar(Hangar hangar)
        {
            Hangar hangar1 = db.Hangers.Find(hangar.ID);
            if (hangar1 != null)
            {
                hangar1.PlaneId = hangar.PlaneId;
                hangar1.Status = hangar.Status;
                db.SaveChanges();
                ViewBag.Message = "Hangar Details Updated Successfully";
                return View("SuccessfullyUpdated");
            }
            return View("Error");
        }

        public ActionResult HangarDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hangar hangar = db.Hangers.Find(id);
            if (hangar == null)
            {
                return HttpNotFound();
            }
            return View(hangar);
        }

        public ActionResult ListOfIssues()
        {
           
            return View(db.Help.ToList());
        }

        public ActionResult ResolveIssue(int? id)
        {
            if(id!=null)
            {
                Help help = db.Help.Find(id);
                return View(help);
            }
            return View("Error");

        }
        [HttpPost]
        public ActionResult ResolveIssue(Help help)
        {
            if(help!=null)
            {
                Help helpCheck = db.Help.Find(help.ID);
                if(helpCheck!=null)
                {
                    helpCheck.Answer = help.Answer;
                    db.SaveChanges();
                    ViewBag.Message = "Issue Resolved Successfully";
                    return View("SuccessfullyUpdated");
                }
                return View("Error");

            }
            return View("Error");
        }

        public ActionResult IssueDetails(int? id)
        {
            if(id!=null)
            {
                Help help = db.Help.Find(id);
                return View(help);
            }

            return View("Error");
        }

        public ActionResult ListOfPreCheckList()
        {
            return View(db.PreCheckLists.ToList());
        }
        public ActionResult ListOfPostCheckList()
        {
            return View(db.PostCheckLists.ToList());
        }

       
    }
}

AirportManagementSystem/Controllers/PilotController.cs
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AirportManagementSystem.Models;

namespace AirportManagementSystem.Controllers
{
    public class PilotController : Controller
    {
        AirportManagementSystemContext db = new AirportManagementSystemContext();
        // GET: Pilot
        public ActionResult Index()
        {
            return View();
        }

        // Home Page Of Pilot
        public ActionResult PilotHomePage()
        {

            return View("PilotHomePage");
        }


        // Create the FlightPlan
        [HttpGet]
        public ActionResult FlightPlan()
        {
           
          ViewBag.WayPointList = new SelectList(db.Waypoints, "ID", "ID");
            ViewBag.PlaneList = new SelectList(db.Planes, "PlaneId", "PlaneId");
            return View();
        }

        [HttpPost]
        public ActionResult FlightPlan(FlightPlan flightPlan)
        {
            if(flightPlan != null)
            {
                db.FlightPlans.Add(flightPlan);
                db.SaveChanges();
                ViewBag.Message = "Your details are submitted Successfully";
                return View("SuccessfullyUpdated");
            }
            else
            {
                return View();
            }
           
        }

        public ActionResult ScheduledPlanes()
        {
           
            return View(from s in db.Schedules orderby s.ScheduleDate orderby s.ScheduleTime descending select s);
        }

        [HttpPost]
        public ActionResult ScheduledPlanes(Schedule schedule)
        {
            return View();
        }


        // For Creation on UI(PreChecklist)
        [HttpGet]
        public ActionResult PreCheckList()
        {
            ViewBag.PlaneList = new SelectList(db.Planes, "PlaneId", "PlaneId");
            return View();
        }


        // For Validation of the PrechecklistEdit

        [HttpPost]
        public ActionResult PreCheckList(PreCheckList preCheckList)
        {
            
            var firstCheck = db.Planes.FirstOrDefault(p => p.PlaneId == preCheckList.YourPlaneId);
            
            if(firstCheck != null)
            {
                if (preCheckList.Power.StartsWith("Ve") && preCheckList.BatteryVoltage.StartsWith("Ve") && preCheckList.BatteryCables.StartsWith("Se")
                && preCheckList.HomeAltitude.StartsWith("Ch") && preCheckList.FlightPlan.StartsWith("As") && preCheckList.GPS.StartsWith("Co")
                    && preCheckList.Antenna.StartsWith("Co") && preCheckList.Speed.StartsWith("Ch"))
                {
                    firstCheck.PlaneStatus = true;
                    db.PreCheckLists.Add(preCheckList);
                    db.SaveChanges();
                    ViewBag.Message = "Pre-CheckList of Plane Checked Successfully";
                    return View("SuccessfullyUpdated");
                }
                else
                {
                    firstCheck.PlaneStatus = false;
                    db.PreCheckLists.Add(preCheckList);
                    db.SaveChanges();
                    ViewBag.Message = "Pre-CheckList of Plane Partially Completed";
                    return View("SuccessfullyUpdated");
                }
            }
            return View("Error");
        }

        public ActionResult ListOfPreCheckList()
        {
            
            return View(db.PreCheckLists.ToList());
        }

        [HttpGet]
        public ActionResult PostCheckList()
        {
            ViewBag.PlaneList = new SelectList(db.Planes, "PlaneId", "PlaneId");
            return View();
        }


        // For Validation of the PrechecklistEdit

        [HttpPost]
        public ActionResult PostCheckList(PostCheckList postCheckList)
        {
            var firstCheck = db.Planes.FirstOrDefault(p => p.PlaneId == postCheckList.YourPlaneId);

            if (firstCheck != null)
            {
                if (postCheckList.Transponder.StartsWith("Ve") && postCheckList.WingFlaps.StartsWith("Ch") && postCheckList.CarbHeat.StartsWith("Se")
               && postCheckList.Lights.StartsWith("On") && postCheckList.Trim.StartsWith("Ve") && postCheckList.Mixture
                .StartsWith("Ch"))
                {
                    firstCheck.PlaneStatus = true;
                    db.PostCheckLists.Add(postCheckList);
                    db.SaveChanges();
                    ViewBag.Message = "Post-CheckList of Plane Checked Successfully";
                    return View("SuccessfullyUpdated");
                }
                else
                {
                    firstCheck.PlaneStatus =false;
                    db.PostCheckLists.Add(postCheckList);
                    db.SaveChanges();
                    ViewBag.Message = "Post-CheckList of Plane Partially Completed";
                    
                    return View("SuccessfullyUpdated");

                }
            }
            return View("Error");
        }

        public ActionResult ListOfPostCheckList()
        {
            
            return View(db.PostCheckLists.ToList());
        }

        public ActionResult ListOfFlightPlan()
        {
            return View(db.FlightPlans.ToList());
        }

        public ActionResult UpdateFlight()
        {
            return View();
        }

        public ActionResult UpdateFlightPlan(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FlightPlan flightPlan = db.FlightPlans.Find(id);
            if (flightPlan == null)
            {
                return HttpNotFound();
            }
            return View(flightPlan);
        }
        [HttpPost]
        public ActionResult UpdateFlightPlan(FlightPlan flightPlan)
        {
            FlightPlan flightPlanCheck = db.FlightPlans.Find(flightPlan.FlightPlanId);
            if(flightPlan != null)
            {
                flightPlanCheck.DepartureLocation = flightPlan.DepartureLocation;
                flightPlanCheck.EDA = flightPlan.EDA;
                flightPlanCheck.ETA = flightPlan.ETA;
                flightPlanCheck.AlternateAirports = flightPlan.AlternateAirports;
                db.SaveChanges();
                ViewBag.Message = "Flight Plan Details Successfully Updated";
                return View("SuccessfullyUpdated");
            }
            return View("Error");
        }


        public ActionResult FlightPlanDetails(int? id)
        {
            if (id != null)
            {
                FlightPlan flightPlan = db.FlightPlans.Find(id);
                return View(flightPlan);
            }
            else
            {
                return View("Error");
            }
        }
            


        public ActionResult DeleteFlightPlan(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FlightPlan flightPlan = db.FlightPlans.Find(id);
            if (flightPlan == null)
            {
                return HttpNotFound();
            }
            return View(flightPlan);
        }

        // POST: AdminPlane/Delete/5
        [HttpPost, ActionName("DeleteFlightPlan")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteFlightPlanConfirmed(int? id)
        {
            FlightPlan flightPlan = db.FlightPlans.Find(id);
            db.FlightPlans.Remove(flightPlan);
            db.SaveChanges();
            return RedirectToAction("PilotHomePage");
        }

       


        public ActionResult ListOfWayPoint()
        {

            return View(db.Waypoints.ToList());
        }

        public ActionResult WayPointDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Waypoint wayPoint = db.Waypoints.FirstOrDefault(w=>w.WaypointId == id);
            if (wayPoint == null)
            {
                return HttpNotFound();
            }
            return View(wayPoint);
        }

        public ActionResult ListOfHangar()
        {

            return View(db.Hangers.ToList());
        }

        public ActionResult ScheduleButtons()
        {
            return View();
        }

        public ActionResult DailySchedule()
        {
            var dailySchedule = (from result in db.Schedules where result.ScheduleDate == DateTime.Now select result).ToList();
            return View(dailySchedule);
        }

        public ActionResult WeeklySchedule()
        {
           
            DateTime date = DateTime.Today.AddDays(6);

            var weeklySchedule = (from result in db.Schedules where date > DateTime.Now select result).ToList();
            return View(weeklySchedule);
        }

        public ActionResult MonthlySchedule()
        {
            DateTime date = DateTime.Today.AddDays(29);
            var monthlySchedule = (from result in db.Schedules where date > DateTime.Now select result).ToList();

            return View(monthlySchedule);
        }


        public ActionResult ListOfIssues()
        {
            return View(db.Help.ToList());
        }

        
    }
}

AirportManagementSystem/Controllers/RegistrationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Data.SqlClient;
using System.Web.Mvc;
using AirportManagementSystem.Models;

namespace AirportManagementSystem.Controllers
{
    public class RegistrationsController : Controller
    {
        AirportManagementSystemContext context = new AirportManagementSystemContext();
        public ActionResult Create()
        {
            int count = (from row in context.Registrations select row).Count();
            if (count > 0)
            {
                TempData["empid"] = count + 1;
            }
            else
            {
                TempData["empid"] = 1;
            }


            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EmployeeId,FirstName,LastName,Gender,DOB,ContactNumber,Password,ConfirmPassword,Designation,SecurityQuestion1,SecurityQuestion2,SecurityQuestion3")] Registration registration)
        {
            if (ModelState.IsValid)
            {
                context.Registrations.Add(registration);
                context.SaveChanges();
                ViewBag.Message = "Registration Successfull";
                return View("SuccessfullyUpdated");
            }

            return View(registration);
        }

       
    }
}

AirportManagementSystem/Views/Shared/SuccessfullyUpdated.cshtml
@{
    ViewBag.Title = "SuccessfullyUpdated";
}

@{ Layout = "~/Views/Shared/_SuccessOrError.cshtml"; }

<br />
<br />
<h2 style="color:green">@Html.ViewBag.Message</h2>

@Html.ActionLink("Back to Home", "Index", "Home", null, null)<br /><br />
@*@Html.ActionLink("Back to Admin Home Page","AdminLoginPage","Home",null,null)*@

AirportManagementSystem/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

<script type="text/javascript">
    function preventBack() { window.history.forward() }
    setTimeout("preventBack()", 0);
    window.onunload = function () { null };
</script>


    
</head>
<body style="background-image: url('https://images.pexels.com/photos/321159/pexels-photo-321159.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940') ">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Admin Account", "AdminLoginPage", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">

                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Admin", "Index", "Home")</li>
        <li>@Html.ActionLink("Employee", "About", "Home")</li>*@
                    <li>@Html.ActionLink("Help", "Help", "Home")</li>

                    <li>@Html.ActionLink("FAQ's", "ListOfIssues", "Home")</li>

                    <li class="pull-right" style="padding-left: 800px;" >
                        @Html.ActionLink("SignOut", "Logout", "Home", null, new { @class = "nav navbar-nav navbar-right" });
                   </li>
                       
                </ul>

            </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <br /><br />
        @Html.ActionLink("Back To Admin Home Page","AdminLoginPage","Home",null,null)
        <hr />
        <footer>
            <b>&copy; @DateTime.Now.Year - Airport Management System</b>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AirportManagementSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type="text/javascript">
        function preventBack() { window.history.forward() }
        setTimeout("preventBack()", 0);
        window.onunload = function () { null };
    </script>
    <br />

    
    
    @*<marquee behavior="scroll" direction="right" scrollamount="16">
        <p style="color:white;font-size: 30px; font-family: Cursive;">Welcome to Airport Management System <img src="~/images/try.png" width="100" height="50" alt="Natural" /></p>
</marquee>*@

   

</head>
<body style="background-image: url('https://images.pexels.com/photos/321159/pexels-photo-321159.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940') ">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Admin", "Index", "Home")</li>
        <li>@Html.ActionLink("Employee", "About", "Home")</li>*@
                    <li>@Html.ActionLink("Help", "Help", "Home")</li>
                    <li>
                        @Html.ActionLink("SignUp!", "Create", "Registrations")
                    </li>
                    <li>@Html.ActionLink("FAQ's", "ListOfIssues", "Home")</li>


                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <br/>
            <br/>
            <b>&copy; @DateTime.Now.Year - Airport Management System</b>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AirportManagementSystem/Views/Shared/_ManagerLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type="text/javascript">
    function preventBack() { window.history.forward() }
    setTimeout("preventBack()", 0);
    window.onunload = function () { null };
    </script>

</head>
<body style="background-image: url('https://images.pexels.com/photos/257416/pexels-photo-257416.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940') ">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Manager Account", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                  
                    <li>@Html.ActionLink("FAQ's", "ListOfIssues", "Home")</li>
                    <li class="pull-right" style="padding-left: 800px;">
                        @Html.ActionLink("SignOut", "Logout", "Home", null, new { @class = "nav navbar-nav navbar-right" });
                    </li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <br />
        <br />
        @Html.ActionLink("Back to Manager Home Page", "ManagerHomePage", "Manager",null,null)
        <hr />
        <footer>
            <b>&copy; @DateTime.Now.Year - Airport Management System</b>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AirportManagementSystem/Views/Shared/_PilotLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type="text/javascript">
    function preventBack() { window.history.forward() }
    setTimeout("preventBack()", 0);
    window.onunload = function () { null };
    </script>

</head>
<body style="background-image: url('https://images.pexels.com/photos/122136/pexels-photo-122136.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940')">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Pilot Account", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    
                    <li>@Html.ActionLink("Help", "Help", "Home")</li>
                   
                    <li>@Html.ActionLink("FAQ's", "ListOfIssues", "Pilot")</li>
                    <li class="pull-right" style="padding-left: 800px;">
                        @Html.ActionLink("SignOut", "Logout", "Home", null, new { @class = "nav navbar-nav navbar-right" });
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <br />
        <br />
        @Html.ActionLink("Back to Pilot Home Page", "PilotHomePage", "Pilot",null,null)
        <hr />
        <footer>
            <b>&copy; @DateTime.Now.Year - Airport Management System</b>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AirportManagementSystem/Views/Shared/_SuccessOrError.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script type="text/javascript">
    function preventBack() { window.history.forward() }
    setTimeout("preventBack()", 0);
    window.onunload = function () { null };
    </script>
</head>
<body style="background-image: url('https://images.pexels.com/photos/321159/pexels-photo-321159.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940') ">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Admin", "Index", "Home")</li>
                        <li>@Html.ActionLink("Employee", "About", "Home")</li>*@
                    <li>@Html.ActionLink("Help", "Contact", "Home")</li>
                    <li>
                        @Html.ActionLink("SignOut", "Index", "Home",null,null);
                    </li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <b>&copy; @DateTime.Now.Year - Airport Management System</b>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>