AirportManagementSystem/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AirportManagementSystem.Models;

namespace AirportManagementSystem.Controllers
{
    
    public class AdminController : Controller
    {
        private AirportManagementSystemContext db = new AirportManagementSystemContext();

        // GET: AdminPlane
        public ActionResult Index()
        {
            return View(db.Planes.ToList());
        }

        // GET: AdminPlane/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plane plane = db.Planes.Find(id);
            if (plane == null)
            {
                return HttpNotFound();
            }
            return View(plane);
        }

        // GET: AdminPlane/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminPlane/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PlaneId,ModelNumber,PurchaseDate,LastServicedDate,PlaneStatus")] Plane plane)
        {
            if (ModelState.IsValid)
            {
                db.Planes.Add(plane);
                db.SaveChanges();
                ViewBag.Message = "Your details are Submitted Successfully";
                return View("SuccessfullyUpdated");
            }

            return View(plane);
        }

        [HttpGet]
        public ActionResult CreateSchedule()
        {
            var pilotlist=(from i in db.Registrations where i.Designation == "Pilot" select i).ToList();
            ViewBag.PilotList = new SelectList(pilotlist, "EmployeeId", "FirstName");
            ViewBag.PlaneList = new SelectList(db.Planes, "PlaneId", "PlaneId");
            return View();
        }

        [HttpPost]
        public ActionResult CreateSchedule(Schedule schedule)
        {
            db.Schedules.Add(schedule);
            db.SaveChanges();
            ViewBag.Message = "Scheduled Successfully";
            return View("SuccessfulMessage");
        }


       
        public ActionResult EditSchedule(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Schedule schedule = db.Schedules.Find(id);
            var pilotlist = (from i in db.Registrations where i.Designation == "Pilot" select i).ToList();
            ViewBag.PilotList = new SelectList(pilotlist, "EmployeeId", "FirstName");
            ViewBag.PlaneList = new SelectList(db.Planes, "PlaneId", "PlaneId");
            if (schedule == null)
            {
                return HttpNotFound();
            }
            return View(schedule);
        }


        // POST: AdminPlane/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditSchedule([Bind(Include = "ScheduleDate,ScheduleTime,AllocatedPlaneId,AllocatedPilotId")] Schedule schedule)
        {
            if (ModelState.IsValid)
            {
               var sch= db.Schedules.FirstOrDefault(s => s.AllocatedPlaneId == schedule.AllocatedPlaneId);
                sch.ScheduleDate = schedule.ScheduleDate;
                sch.ScheduleTime = sch.ScheduleTime;
                db.SaveChanges();
                ViewBag.Message = "You details submitted Successfully";
                return View("SuccessfullyUpdated");
            }
            return View(schedule);
            
        }

        public ActionResult ListOfSchedule()
        {
           
            return View(db.Schedules.ToList());
        }
        
        [HttpGet]
        public ActionResult CreateHangars()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateHangars(Hangar hangar)
        {
          
                  
                    db.Hangers.Add(hangar);
                    hangar.Status = false;
                    db.SaveChanges();
                    ViewBag.Message = "Plane allocated to Hangar Successfully";
                    return View("SuccessfulMessage");
               
           
        }


        public ActionResult ListOfHangar()
        {
            
            return View(db.Hangers.ToList());
        }

        //public ActionResult UpdateHangar(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Hangar hangar = db.Hangers.Find(id);
        //    if (hangar == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(hangar);
        //}

        //[HttpPost]
        //public ActionResult UpdateHangar(Hangar hangar)
        //{
        //    Hangar hangar1 = db.Hangers.Find(hangar.HangarId);
        //    if(hangar1!=null)
        //    {
        //        hangar1.PlaneId = hangar.PlaneId;
        //        hangar1.Status = hangar.Status;
        //        db.SaveChanges();
        //        ViewBag.Message="Hangar Details Updated Successfully";
        //        return View("SuccessfulMessage");
        //    }
        //    return View("Error");
        //}

        public ActionResult HangarDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hangar hangar = db.Hangers.FirstOrDefault(h=>h.HangarId == id);
            if (hangar == null)
            {
                return HttpNotFound();
            }
            return View(hangar);
        }



       


        public ActionResult CreateWayPoint()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateWayPoint(Waypoint wayPoint)
        {
            if (wayPoint != null)
            {
                db.Waypoints.Add(wayPoint);
                db.SaveChanges();
                ViewBag.Message = "WayPoint Created Successfully";
                return View("SuccessfullyUpdated");
            }
            return View("Error");
        }






        public ActionResult ListOfWayPoint()
        {
           
            return View(db.Waypoints.ToList());
        }

        public ActionResult UpdateWayPoint(int? id)
        {
            if(id!=null)
            {
                Waypoint wayPoint = db.Waypoints.Find(id);
                return View(wayPoint);
            }
            return View("Error");
        }

        [HttpPost]
        public ActionResult UpdateWayPoint(Waypoint wayPoint)
        {
            Waypoint wayPointDB = db.Waypoints.FirstOrDefault(w=>w.ID == wayPoint.ID);
            
                              
                wayPointDB.Altitude = wayPoint.Altitude;
                wayPointDB.Latitude = wayPoint.Latitude;
                wayPointDB.Longitude = wayPoint.Longitude;
                wayPointDB.Speed = wayPoint.Speed;
                db.SaveChanges();
                ViewBag.Message = "Way Point Details Updated Successfully";
                return View("SuccessfulMessage");
            
        }

        public ActionResult WayPointDetails(int? id)
        {
            if(id!=null)
            {
                Waypoint wayPoint = db.Waypoints.FirstOrDefault(w=>w.WaypointId == id);
                return View(wayPoint);
            }
            return View("Error");
        }

        public ActionResult DeleteWayPoint(int? id)
        {
            if(id!=null)
            {
                Waypoint wayPoint = db.Waypoints.FirstOrDefault(w => w.WaypointId == id);
                return View(wayPoint);
            }

            return View("Error");
        }
        [HttpPost, ActionName("DeleteWayPoint")]
        public ActionResult ConfirmDeleteWayPoint(int? id)
        {
            if(id!=null)
            {
                Waypoint wayPoint = db.Waypoints.Find(id);
                if(wayPoint!=null)
                {
                    db.Waypoints.Remove(wayPoint);
                    db.SaveChanges();
                    ViewBag.Message = "WayPoint Deleted Successfully";
                    return View("SuccessfulMessage");
                }
                return View("Error");
            }
            return View("Error");

        }

        


        // GET: AdminPlane/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Plane plane = db.Planes.Find(id);
            if (plane == null)
            {
                return HttpNotFound();
            }
            return View(plane);
        }


        // POST: AdminPlane/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PlaneId,ModelNumber,PurchaseDate,LastServicedDate,PlaneStatus")] Plane plane)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(plane).State = EntityState.Modified;
                var validation = db.Planes.FirstOrDefault(p => p.PlaneId == plane.PlaneId);
                validation.LastServicedDate = plane.LastServicedDate;

AirportManagementSystem/Controllers/CrudRegistrationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AirportManagementSystem.Models;

namespace AirportManagementSystem.Controllers
{
    public class CrudRegistrationController : Controller
    {
        private AirportManagementSystemContext db = new AirportManagementSystemContext();

        
        // GET: CrudRegistration
        public ActionResult List()
        {
            var output = db.Registrations.ToList();
            return View("List",output);
        }

        // GET: CrudRegistration/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Registration registration = db.Registrations.Find(id);
            if (registration == null)
            {
                return HttpNotFound();
            }
            return View(registration);
        }

        // GET: CrudRegistration/Create
        public ActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EmployeeId,FirstName,LastName,Gender,DOB,ContactNumber,Password,ConfirmPassword,Designation,SecurityQuestion1,SecurityQuestion2,SecurityQuestion3,Active")] Registration registration)
        {
            if (ModelState.IsValid)
            {
                db.Registrations.Add(registration);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(registration);
        }

        // GET: CrudRegistration/Edit/5
        public ActionResult Approve(int? id)
        {
            if (id != null)
            {
                var registration = db.Registrations.FirstOrDefault(x => x.EmployeeId == id);
                //Registration registration = db.Registrations.Find(id);
                if (registration != null)
                {
                    registration.Active = true;
                    db.SaveChanges();
                    ViewBag.Message = "Approved Successfully";
                    return View("SuccessfullyUpdated");
                }
                return View("Error");
            }
            return View("Error");
            
           
        }

        public ActionResult Deny(int? id)
        {
            if (id != null)
            {
                var registration = db.Registrations.FirstOrDefault(x => x.EmployeeId == id);
                //Registration registration = db.Registrations.Find(id);
                if (registration != null)
                {
                    registration.Active = false;
                    db.SaveChanges();
                    ViewBag.Message = "Denied the Request";
                    return View("SuccessfullyUpdated");
                }
                return View("Error");
            }
            return View("Error");


        }

        // POST: CrudRegistration/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EmployeeId,FirstName,LastName,Gender,DOB,ContactNumber,Password,ConfirmPassword,Designation,SecurityQuestion1,SecurityQuestion2,SecurityQuestion3,Active")] Registration registration)
        {
            if (ModelState.IsValid)
            {
                db.Entry(registration).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(registration);
        }

        // GET: CrudRegistration/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Registration registration = db.Registrations.Find(id);
            if (registration == null)
            {
                return HttpNotFound();
            }
            return View(registration);
        }

        // POST: CrudRegistration/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Registration registration = db.Registrations.Find(id);
            db.Registrations.Remove(registration);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AirportManagementSystem/Views/CrudRegistration/Create.cshtml
@model AirportManagementSystem.Models.Registration

@{
    ViewBag.Title = "Create";
}

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Registration</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Gender, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Designation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Designation, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Designation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SecurityQuestion1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SecurityQuestion1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SecurityQuestion1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SecurityQuestion2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SecurityQuestion2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SecurityQuestion2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SecurityQuestion3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SecurityQuestion3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SecurityQuestion3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Active, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AirportManagementSystem/Views/CrudRegistration/Delete.cshtml
@model AirportManagementSystem.Models.Registration

@{
    ViewBag.Title = "Delete";
}

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Registration</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DOB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConfirmPassword)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConfirmPassword)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Designation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Designation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecurityQuestion1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecurityQuestion1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecurityQuestion2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecurityQuestion2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecurityQuestion3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecurityQuestion3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-success" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AirportManagementSystem/Views/CrudRegistration/Details.cshtml
@model AirportManagementSystem.Models.Registration

@{
    ViewBag.Title = "Details";
}

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Registration</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DOB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DOB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConfirmPassword)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConfirmPassword)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Designation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Designation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecurityQuestion1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecurityQuestion1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecurityQuestion2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecurityQuestion2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecurityQuestion3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecurityQuestion3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Active)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Active)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EmployeeId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AirportManagementSystem/Views/CrudRegistration/List.cshtml
@model IEnumerable<AirportManagementSystem.Models.Registration>

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@ViewBag.Message

@if (Session["user"] == null)
{
  <br/>
  <h4>@Html.ActionLink("Please Login Again", "Admin", "Home")</h4>

}
else
{
    <h2>Index</h2>

    <p>
        @*@Html.ActionLink("Create New", "Create");*@
    </p>
    <table class="table table-hover">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DOB)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContactNumber)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.Password)
                </th>*@
            @*<th>
                    @Html.DisplayNameFor(model => model.ConfirmPassword)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Designation)
            </th>
            @*<th>
                    @Html.DisplayNameFor(model => model.SecurityQuestion1)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SecurityQuestion2)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SecurityQuestion3)
                </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Active)
            </th>
            <th>Status</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Gender)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DOB)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ContactNumber)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.Password)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ConfirmPassword)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.Designation)
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.SecurityQuestion1)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SecurityQuestion2)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SecurityQuestion3)
                    </td>*@
                <td>
                    @Html.DisplayFor(modelItem => item.Active)
                </td>
                <td>
                    @Html.ActionLink("Approve", "Approve", "CrudRegistration", new { id = item.EmployeeId }, null)|
                    @Html.ActionLink("Deny", "Deny", "CrudRegistration", new { id = item.EmployeeId }, null)

                </td>


            </tr>


        }


    </table>
}